controller_manager:
  ros__parameters:
    update_rate: 50 #hz

  joint_state_broadcaster:
    type: joint_state_broadcaster/JointStateBroadcaster

  mecanum_drive_controller:
    type: mecanum_drive_controller/MecanumDriveController

  forward_position_controller:
    type: forward_command_controller/ForwardCommandController

mecanum_drive_controller:
  ros__parameters:
    front_left_wheel_command_joint_name: "front_left_axle"
    front_right_wheel_command_joint_name: "front_right_axle"
    rear_right_wheel_command_joint_name: "rear_right_axle"
    rear_left_wheel_command_joint_name: "rear_left_axle"

    kinematics:
      x: 0
      y: 0
      theta: 0

    wheels_radius: 0.075 #75mm

forward_position_controller:
  ros__parameters:
    joints:
      - reader_shoulder_joint
      - reader_elbow_joint
    interface_name: position
    

